
/**:
  ros__parameters:
    camera:
      i_enable_rgb: true
      i_enable_left: true
      i_enable_right: true
      i_enable_depth: true
      i_publish_tf: true
      i_tf_base_frame: "base_link"
      i_tf_camera_frame: "oakd_frame"
      i_enable_imu: false
      i_enable_nn_sync: false

    rgb:
     i_fps: 30
     i_resolution: "1080P"
     i_update_ae: true
     i_update_awb: true


    stereo:
     i_fps: 30
     i_depth_align: "RGB"
     i_enable_distortion_correction: true
     i_subpixel: true
     i_lr_check: true
     i_extended_disp: false

     
    pointcloud:
     i_enable: true
   